### ISSUE TITLE
Error: No signatures were specified.

### ISSUE THREAD

**Issue by plasmak** [chrisallenlane/drek#4]
OS : Windows 7, node v8.9.1, installed drek via npm.

Command : 
PS C:\drek-signatures\signatures> drek "C:\myapp\" -s ".\php.yml" -p "myapp" > drek_myapp.html

Output: 
Error: No signatures were specified.
    at module.exports (C:\Users\me\AppData\Roaming\npm\node_modules\drek\app\util-load-signatures.js:20:11)
    at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\drek\app\index.js:27:53)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

Makes no sense to me.

**Comment by flex0geek** [comment]
Hi plasmak, did you solve this issue?!
